[env:nucleo_l476rg]
platform = ststm32
board = nucleo_l476rg
framework = stm32cube

; Memory Offset and Python Script configurations
build_flags = 
    -DUSER_VECT_TAB_ADDRESS
    -DVECT_TAB_OFFSET=0x8000
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -mfloat-abi=softfp
board_build.ldscript = app_offset.ld
extra_scripts = post:inject_crc.py
monitor_speed = 115200
; Force OpenOCD to upload the .bin file
upload_protocol = custom
upload_command = $PROJECT_PACKAGES_DIR/tool-openocd/bin/openocd -f interface/stlink.cfg -f target/stm32l4x.cfg -c "program .pio/build/nucleo_l476rg/firmware.bin 0x08008000 verify reset exit"